// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/jinzhu/gorm"
)

const TableNameCategory = "categories"

// Category mapped from table <categories>
type Category struct {
	ID        int32  `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Name      string `gorm:"column:name;type:varchar(50);not null" json:"name"`
	UserID int32  `gorm:"column:user_id;type:int(11);not null" json:"user_id"`
	Image     string `gorm:"column:image;type:text;not null" json:"image"`
	CreatedAt int32  `gorm:"column:created_at;type:int(11);not null" json:"created_at"`
	UpdatedAt int32  `gorm:"column:updated_at;type:int(11);not null" json:"updated_at"`
}

func (i *Category) BeforeCreate(scope *gorm.Scope) error {
    now := int32(time.Now().Unix())
    i.CreatedAt = now

    return nil
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
