// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMethod = "methods"

// Method mapped from table <methods>
type Method struct {
	ID        int32  `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Name      string `gorm:"column:name;type:varchar(50);not null" json:"name"`
	CreatedAt int32  `gorm:"column:created_at;type:int(11);not null" json:"created_at"`
	UpdatedAt int32  `gorm:"column:updated_at;type:int(11);not null" json:"updated_at"`
}

// TableName Method's table name
func (*Method) TableName() string {
	return TableNameMethod
}
