// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/jinzhu/gorm"
)

const TableNameMidtransNotification = "midtrans_notification"

// MidtransNotification mapped from table <midtrans_notification>
type MidtransNotification struct {
	ID                int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	OrderID           *int32  `gorm:"column:order_id;type:int(11);index:order_id,priority:1" json:"order_id"`
	OrderUUID         *string `gorm:"column:order_uuid;type:varchar(36)" json:"order_uuid"`
	SignatureKey      *string `gorm:"column:signature_key;type:varchar(255)" json:"signature_key"`
	TransactionID     *string `gorm:"column:transaction_id;type:varchar(36)" json:"transaction_id"`
	TransactionTime   *string `gorm:"column:transaction_time;type:varchar(255)" json:"transaction_time"`
	TransactionStatus *string `gorm:"column:transaction_status;type:varchar(255)" json:"transaction_status"`
	FraudStatus       *string `gorm:"column:fraud_status;type:varchar(255)" json:"fraud_status"`
	PaymentType       *string `gorm:"column:payment_type;type:varchar(255)" json:"payment_type"`
	GrossAmount       *int64  `gorm:"column:gross_amount;type:int(11)" json:"gross_amount"`
	Raw               *string `gorm:"column:raw;type:text" json:"raw"`
	CreatedAt         *int32  `gorm:"column:created_at;type:int(11)" json:"created_at"`
	UpdatedAt         *int32  `gorm:"column:updated_at;type:int(11)" json:"updated_at"`
}

type InputMidtransNotification struct {
	OrderID         *int32  `gorm:"column:payment_id;type:int(11);index:order_id,priority:1" json:"order_uuid"`
	OrderUUID       *string `gorm:"column:payment_uuid;type:varchar(36)" json:"order_id"`
	SignatureKey      *string `gorm:"column:signature_key;type:varchar(255)" json:"signature_key"`
	TransactionID     *string `gorm:"column:transaction_id;type:varchar(36)" json:"transaction_id"`
	TransactionTime   *string `gorm:"column:transaction_time;type:varchar(255)" json:"transaction_time"`
	TransactionStatus *string `gorm:"column:transaction_status;type:varchar(255)" json:"transaction_status"`
	FraudStatus       *string `gorm:"column:fraud_status;type:varchar(255)" json:"fraud_status"`
	PaymentType       *string `gorm:"column:payment_type;type:varchar(255)" json:"payment_type"`
	GrossAmount       *string  `gorm:"column:gross_amount;type:int(11)" json:"gross_amount"`
	CreatedAt         *int32  `gorm:"column:created_at;type:int(11)" json:"created_at"`
}

func (i *MidtransNotification) BeforeCreate(scope *gorm.Scope) error {
    now := int32(time.Now().Unix())
    i.CreatedAt = &now

    return nil
}

// TableName MidtransNotification's table name
func (*MidtransNotification) TableName() string {
	return TableNameMidtransNotification
}
