// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/jinzhu/gorm"
)

const TableNameMotif = "motifs"

// Motif mapped from table <motifs>
type Motif struct {
	ID        int32  `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Name      string `gorm:"column:name;type:varchar(50);not null" json:"name"`
	ProductID int32  `gorm:"column:product_id;type:int(11);not null" json:"product_id"`
	Price     int32  `gorm:"column:price;type:int(11);not null" json:"price"`
	Image     string `gorm:"column:image;type:text;not null" json:"image"`
	CreatedAt int32  `gorm:"column:created_at;type:int(11);not null" json:"created_at"`
	UpdatedAt int32  `gorm:"column:updated_at;type:int(11);not null" json:"updated_at"`
}

func (i *Motif) BeforeCreate(scope *gorm.Scope) error {
    now := int32(time.Now().Unix())
    i.CreatedAt = now

    return nil
}


// TableName Motif's table name
func (*Motif) TableName() string {
	return TableNameMotif
}
