// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/jinzhu/gorm"
)

const TableNameOrder = "order"

// Order mapped from table <order>
type Order struct {
	ID                   int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	UUID                 *string `gorm:"column:uuid;type:varchar(255)" json:"uuid"`
	UserID               int32   `gorm:"column:user_id;type:int(11);not null;index:user_id,priority:1" json:"user_id"`
	PackageID            *int32  `gorm:"column:package_id;type:int(11);index:package_id,priority:1" json:"package_id"`
	BundleID             *int32  `gorm:"column:bundle_id;type:int(11);index:bundle_id,priority:1" json:"bundle_id"`
	Amount               *int32  `gorm:"column:amount;type:int(11)" json:"amount"`
	CancelledAt          *int32  `gorm:"column:cancelled_at;type:int(11)" json:"cancelled_at"`
	ExpiredAt            *int32  `gorm:"column:expired_at;type:int(11)" json:"expired_at"`
	CheckedOutAt         *int32  `gorm:"column:checked_out_at;type:int(11)" json:"checked_out_at"`
	MidtransPaymentToken *string `gorm:"column:midtrans_payment_token;type:text" json:"midtrans_payment_token"`
	MidtransPaymentURL   *string `gorm:"column:midtrans_payment_url;type:text" json:"midtrans_payment_url"`
	PaidAt               *int32  `gorm:"column:paid_at;type:int(11)" json:"paid_at"`
	CreatedAt            *int32  `gorm:"column:created_at;type:int(11)" json:"created_at"`
	UpdatedAt            *int32  `gorm:"column:updated_at;type:int(11)" json:"updated_at"`
	CreatedBy            *int32  `gorm:"column:created_by;type:int(11);index:created_by,priority:1" json:"created_by"`
	UpdatedBy            *int32  `gorm:"column:updated_by;type:int(11);index:updated_by,priority:1" json:"updated_by"`
	Package               Package `gorm:"foreignkey:PackageID" json:"Package"`
}

type Order1 struct {
	ID                   int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	UUID                 *string `gorm:"column:uuid;type:varchar(255)" json:"uuid"`
	UserID               *int32  `gorm:"column:user_id;type:int(11);index:user_id,priority:1" json:"user_id"`
	PackageID            *int32  `gorm:"column:package_id;type:int(11);index:event_id,priority:1" json:"package_id"`
	CreatedAt            *int32  `gorm:"column:created_at;type:int(11)" json:"created_at"`
}

type Order2 struct {
	Amount               *int32  `gorm:"column:amount;type:int(11)" json:"amount"`
	PaidAt               *int32  `gorm:"column:paid_at;type:int(11)" json:"paid_at"`
}

type Order3 struct {
	Amount               *int32  `gorm:"column:amount;type:int(11)" json:"amount"`
	MidtransPaymentToken *string `gorm:"column:midtrans_payment_token;type:text" json:"midtrans_payment_token"`
	MidtransPaymentURL   *string `gorm:"column:midtrans_payment_url;type:text" json:"midtrans_payment_url"`
}

type Order4 struct {
	ID                   int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	UUID                 *string `gorm:"column:uuid;type:varchar(255)" json:"uuid"`
	UserID               *int32  `gorm:"column:user_id;type:int(11);index:user_id,priority:1" json:"user_id"`
	Amount               *int32  `gorm:"column:amount;type:int(11)" json:"amount"`
	CancelledAt          *int32  `gorm:"column:cancelled_at;type:int(11)" json:"cancelled_at"`
	ExpiredAt            *int32  `gorm:"column:expired_at;type:int(11)" json:"expired_at"`
	CheckedOutAt         *int32  `gorm:"column:checked_out_at;type:int(11)" json:"checked_out_at"`
	PaidAt               *int32  `gorm:"column:paid_at;type:int(11)" json:"paid_at"`
	MidtransPaymentURL   *string `gorm:"column:midtrans_payment_url;type:text" json:"midtrans_payment_url"`
}


type Order5 struct {
	CountQuestion               *int32  `gorm:"column:countquestion" json:"countquestion"`
}

type Order6 struct {
	PackageID            *int32  `gorm:"column:package_id;type:int(11);index:event_id,priority:1" json:"package_id"`
	Amount               int  `json:"amount"`
}

type Order7 struct {
    ID                   int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
}

type Order8 struct {
  ID                   int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
}




func (i *Order1) BeforeCreate(scope *gorm.Scope) error {
    now := int32(time.Now().Unix())
    i.CreatedAt = &now

    return nil
}


// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
func (*Order1) TableName() string {
	return TableNameOrder
}

func (*Order2) TableName() string {
	return TableNameOrder
}

func (*Order3) TableName() string {
	return TableNameOrder
}

func (*Order4) TableName() string {
	return TableNameOrder
}

func (*Order5) TableName() string {
	return TableNameOrder
}




