// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePackage = "package"

// Package mapped from table <package>
type Package struct {
	ID        int32  `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	MotifID   int32  `gorm:"column:motif_id;type:int(11);not null" json:"motif_id"`
	SizeID    int32  `gorm:"column:size_id;type:int(11);not null" json:"size_id"`
	ProductID int32  `gorm:"column:product_id;type:int(11);not null" json:"product_id"`
	MethodID  int32  `gorm:"column:method_id;type:int(11);not null" json:"method_id"`
	Note      string `gorm:"column:note;type:text;not null" json:"note"`
	Address   string `gorm:"column:address;type:text;not null" json:"address"`
	CreatedAt int32  `gorm:"column:created_at;type:int(11);not null" json:"created_at"`
	UpdatedAt int32  `gorm:"column:updated_at;type:int(11);not null" json:"updated_at"`
}

// TableName Package's table name
func (*Package) TableName() string {
	return TableNamePackage
}
