// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePayment = "payment"

// Payment mapped from table <payment>
type Payment struct {
	ID                   int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	UUID                 *string `gorm:"column:uuid;type:varchar(255)" json:"uuid"`
	UserID               *int32  `gorm:"column:user_id;type:int(11);index:user_id,priority:1" json:"user_id"`
	PackageID            *int32  `gorm:"column:package_id;type:int(11);index:event_id,priority:1" json:"package_id"`
	Amount               *int32  `gorm:"column:amount;type:int(11)" json:"amount"`
	CancelledAt          *int32  `gorm:"column:cancelled_at;type:int(11)" json:"cancelled_at"`
	ExpiredAt            *int32  `gorm:"column:expired_at;type:int(11)" json:"expired_at"`
	CheckedOutAt         *int32  `gorm:"column:checked_out_at;type:int(11)" json:"checked_out_at"`
	MidtransPaymentToken *string `gorm:"column:midtrans_payment_token;type:text" json:"midtrans_payment_token"`
	MidtransPaymentURL   *string `gorm:"column:midtrans_payment_url;type:text" json:"midtrans_payment_url"`
	PaidAt               *int32  `gorm:"column:paid_at;type:int(11)" json:"paid_at"`
	CreatedAt            *int32  `gorm:"column:created_at;type:int(11)" json:"created_at"`
	UpdatedAt            *int32  `gorm:"column:updated_at;type:int(11)" json:"updated_at"`
	CreatedBy            *int32  `gorm:"column:created_by;type:int(11);index:created_by,priority:1" json:"created_by"`
	UpdatedBy            *int32  `gorm:"column:updated_by;type:int(11);index:updated_by,priority:1" json:"updated_by"`
}

// TableName Payment's table name
func (*Payment) TableName() string {
	return TableNamePayment
}
