// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/jinzhu/gorm"
)

const TableNameProduct = "products"

// Product mapped from table <products>
type Product struct {
	ID         int32  `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	CategoryID int32  `gorm:"column:category_id;type:int(11);not null" json:"category_id"`
	UserID int32  `gorm:"column:user_id;type:int(11);not null" json:"user_id"`
	Name       string `gorm:"column:name;type:varchar(50);not null" json:"name"`
	Deskripsi  string `gorm:"column:deskripsi;type:text;not null" json:"deskripsi"`
	Price      int32  `gorm:"column:price;type:int(11);not null" json:"price"`
	Stock      int32  `gorm:"column:stock;type:int(11);not null" json:"stock"`
	Weight     int32  `gorm:"column:weight;type:int(11);not null" json:"weight"`
	Image      string `gorm:"column:image;type:text;not null" json:"image"`
	CreatedAt  int32  `gorm:"column:created_at;type:int(11);not null" json:"created_at"`
	UpdatedAt  int32  `gorm:"column:updated_at;type:int(11);not null" json:"updated_at"`
}


func (i *Product) BeforeCreate(scope *gorm.Scope) error {
    now := int32(time.Now().Unix())
    i.CreatedAt = now

    return nil
}

// TableName Product's table name
func (*Product) TableName() string {
	return TableNameProduct
}
