// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/jinzhu/gorm"
)

const TableNameSize = "sizes"

// Size mapped from table <sizes>
type Size struct {
	ID        int32  `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Name      string `gorm:"column:name;type:varchar(50);not null" json:"name"`
	ProductID int32  `gorm:"column:product_id;type:int(11);not null" json:"product_id"`
	CreatedAt int32  `gorm:"column:created_at;type:int(11);not null" json:"created_at"`
	UpdatedAt int32  `gorm:"column:updated_at;type:int(11);not null" json:"updated_at"`
}

func (i *Size) BeforeCreate(scope *gorm.Scope) error {
    now := int32(time.Now().Unix())
    i.CreatedAt = now

    return nil
}

// TableName Size's table name
func (*Size) TableName() string {
	return TableNameSize
}
